version: '3'

services:
  postgres:
    build:
      context: .
      args:
        - "CURRENT_UID=${CURRENT_UID:-1000}"
        - "CURRENT_GID=${CURRENT_GID:-1000}"
    user: ${CURRENT_UID:-1000}:${CURRENT_GID:-1000}
    container_name: postgres
    restart: unless-stopped
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "DB_CONN_SYNC=${DB_CONN_SYNC}"
      - "DB_CONN_ASYNC=${DB_CONN_ASYNC}"
      - "HOST=${HOST}"
      - "PORT=${PORT}"
      - "QUART_ENV=${QUART_ENV}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "PYTHONUNBUFFERED=1"
    shm_size: 2gb
    volumes:
      - "./data/postgres:/var/lib/postgresql/data/:rw"
      - "./data/backups:/backups:rw"
      - "./data/logs:/logs:rw"
    networks:
      - "pgadmin"
    ports:
      - "5432:${POSTGRES_PORT}"
      - "5001:5000" # Debug port forwarding for testing of Rest API
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: no
    profiles:
      - pgadmin
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}"
    volumes:
      - "${PGADMIN_ROOT}/pgadmin:/var/lib/pgadmin"
    networks:
      - "pgadmin"
    ports:
      - "8080:80"

networks:
  pgadmin:
    external: false